const songs = [
    {
      id: 1,
      name: "Hari Hara Veeramallu",
      description: "Best rock songs of the decade",
      image: "./src/assets/veeramallu.jpg",
      songs: [
        {
          id: 1,
          title: "Kollagottinadhiro...",
          artist: "Queen",
          src: "./src/assets/songs/V-Kollagottinadhiro.mp3",
          image:  "./src/assets/veeramallukollagottinadgiro.jpg",
          category: "Top Songs", 
        },
        {
          id: 2,
          title: "Maata Vinali",
          artist: "Eagles",
          src: "./src/assets/songs/V-Maata-Vinaali.mp3",
          image:  "./src/assets/veeramallumaatavinali.jpg",
          category: "Newly Released", 
        },
          {
          id: 3,
          title: "Taara Taaraa",
          artist: "Eagles",
          src: "./src/assets/songs/V-Taara-Taara.mp3",
          image:  "./src/assets/veeramallu-tara-tara.jpeg",
          category: "Newly Released", 
        },

      ],
    },
    {
      id: 3,
      name: "Thug Life",
      description: "Top pop songs",
      image: "./src/assets/thuglife.jpeg",
      songs: [
        {
          id: 1,
          title: "Jinguchaa",
          artist: "Ed Sheeran",
          src: "./src/assets/songs/T-jinguchaa.mp3",
          image: "./src/assets/jingucha.jpeg",
          category: "Top Songs", 
        },
        {
          id: 2,
          title: "Muddu Vaana",
          artist: "The Weeknd",
          src: "./src/assets/songs/T-Muddu-Vaana.mp3",
          image:  "./src/assets/thuglife.jpeg",
          category: "Newly Released", 
        },
           {
          id: 3,
          title: "Sugar Baby",
          artist: "The Weeknd",
          src: "./src/assets/songs/T-Sugar-Baby.mp3",
          image:  "./src/assets/sugarbaby.jpg",
          category: "Newly Released", 
        },
      ],
    },
    {
      id: 4,
      name: "HIT 3",
      description: "Top Telugu songs",
      image:  "./src/assets/hit.jpeg",
      songs: [
        {
          id: 1,
          title: "Prema Velluva",
          artist: "Armaan Malik",
          src: "./src/assets/songs/HPremaVelluva.mp3",
          image:  "./src/assets/premavelluva.jpeg",
          category: "Telugu Songs", 
        },
        {
          id: 2,
          title: "Poratame BGM",
          artist: "Sid Sriram",
          src: "./src/assets/songs/HPoratame.mp3",
          image:  "./src/assets/poratame.jpeg",
          category: "Telugu Songs", 
        },
         {
          id: 3,
          title: "Thanu",
          artist: "Sid Sriram",
          src: "./src/assets/songs/HThanu.mp3",
          image:  "./src/assets/thanu.jpeg",
          category: "Telugu Songs", 
        },
      ],
    },
    {
      id: 5,
      name: "Pushpa 2",
      description: "Latest Hindi songs",
      image:  "./src/assets/pushpa2.jpeg",
      songs: [
        {
          id: 1,
          title: "Pushpa Pushpa",
          artist: "Arijit Singh",
          src: "./src/assets/songs/Pushpa2pushpaa.mp3",
          image:  "./src/assets/pushpa2.jpeg",
          category: "Hindi Songs", 
        },
        {
          id: 2,
          title: "Sooseki",
          artist: "Arijit Singh",
          src: "./src/assets/songs/pushpa2Sooseki.mp3",
          image:  "./src/assets/pushpa2suseki.jpeg",
          category: "Hindi Songs", 
        },
         {
          id: 3,
          title: "Kissik",
          artist: "Arijit Singh",
          src: "./src/assets/songs/pushpa2Kissik.mp3",
          image:  "./src/assets/pushpa2kissik.jpeg",
          category: "Hindi Songs", 
        },
      ],
    },
    {
      id: 6,
      name: "Sardaar Gabbarsingh",
      description: "Latest Hindi songs",
      image:  "./src/assets/sardaargabbarsing.jpeg",
      songs: [
        {
          id: 1,
          title: "sardaar Gabbarsing",
          artist: "Arijit Singh",
          src: "./src/assets/songs/Sardaar.mp3",
          image:  "./src/assets/sardaargabbarsing.jpeg",
          category: "Hindi Songs", 
        },
        {
          id: 2,
          title: "Khakee Chokka",
          artist: "Arijit Singh",
          src: "./src/assets/songs/KhakeeChokka.mp3",
          image:  "./src/assets/khakeechokka.jpeg",
          category: "Hindi Songs", 
        },
         {
          id: 3,
          title: "tauba Tauba",
          artist: "Arijit Singh",
          src: "./src/assets/songs/TaubaTauba.mp3",
          image:  "./src/assets/taubatauba.jpeg",
          category: "Hindi Songs", 
        },
      ],
    },
  ];


  export default songs